name: super_markdown
description: "Markdown + LaTeX math + chemistry renderer for Flutter"
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3
  markdown: ^7.0.0
  flutter_math_fork: ^0.7.0

flutter:
  uses-material-design: true
